### PR TITLE
fix: unstable hosts array

### LINKED ISSUE #65: bug: route.hosts uses `set.StringSet` breaks diff
https://github.com/api7/apisix-mesh-agent/blob/master/pkg/adaptor/xds/v3/route.go#L90-L90

`proto.Equal` doesn't check array order.

### PR DESCRIPTION
**Pull request by lingsamuel**
fixes #65

### CODE REVIEW

**Review by tokers — APPROVED** [review]

File: pkg/adaptor/xds/v3/route_test.go [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package v3
 
 import (
+	apisixutil "github.com/api7/apisix-mesh-agent/pkg/apisix"
```
Comment (tokers) [inline pkg/adaptor/xds/v3/route_test.go:4]: Put this package to the bottom of the `import` block.

**Review by tokers — APPROVED** [review]
